name: projetagri
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-290.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  bloc:
  equatable: ^2.0.5
  path_provider: ^2.0.13
  hydrated_bloc: ^9.1.0
  flutter_svg:
  google_fonts:
  intl:
  mongo_dart: ^0.8.2

  shared_preferences:
  flutter_spinkit: ^5.1.0
  curved_navigation_bar: ^1.0.3
  dropdown_button2: ^1.9.3
  readmore: ^2.2.0

  
  built_value_generator:
  intl_phone_field:
  fl_country_code_picker:
  line_awesome_flutter: ^2.0.0
  

  rxdart:
  json_serializable:
  json_annotation:
  app_settings:
  flutter_settings_screens:
  basic_utils:
  flutter_map:
  flutter_map_marker_cluster:
  get_storage:
  connectivity_plus: ^3.0.3    #for cheking the wifi connection

  # Google Maps and Places autocomplete APIs

  get:
  http: any

  geolocator:

  # to get the address from the logtitude and latitude

  geocoding:

  google_maps_flutter:
  flutter_typeahead:

  flutter_google_places:
  charts_flutter:




  # SPLASH SCREEN
  flutter_native_splash:



  

  # chart
  syncfusion_flutter_charts:






  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner: ^2.4.1
  mobx_codegen:
  flutter_native_splash:
flutter_native_splash:  
  image: images/logo.png
  color : "#FFFFFF"
  fullscreen: true
  android_gravity: center
  fill: true
  android: true
  ios: true
  scale: 2.5
  ios_content_mode: center



flutter:
  assets:
    - images/nointernetpic.png
    - images/


  uses-material-design: true



  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
